# Generated by Django 3.1.6 on 2021-04-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('raca', models.CharField(max_length=255)),
                ('especie', models.CharField(max_length=255)),
                ('peso', models.CharField(max_length=14)),
                ('dataNascimento', models.CharField(max_length=14)),
                ('donoPet', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
