# Generated by Django 3.1.6 on 2021-04-29 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20210428_2309'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pet',
            new_name='Animals',
        ),
    ]
