# Generated by Django 3.2 on 2021-05-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20210428_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
